export default [
    {
        id: 0,
        name: 'Chandler Bing',
        message: 'Pitch termsheet backing validation focus release.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a1.jpg',
        image: '/img/blog/b1.jpg',
    },
    {
        id: 1,
        name: 'Rachel Green',
        message: 'Seed round direct mailing non-disclosure agreement graphical user interface rockstar.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a2.jpg',
        image: '/img/blog/b2.jpg',
    },
    {
        id: 2,
        name: 'Monica Geller',
        message: 'Beta prototype sales iPad gen-z marketing network effects value proposition',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a3.jpg',
        image: '/img/blog/b3.jpg',
    },
    {
        id: 3,
        name: 'Chandler Bing',
        message: 'Pitch termsheet backing validation focus release.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a1.jpg',
        image: '/img/blog/b1.jpg',
    },
    {
        id: 4,
        name: 'Rachel Green',
        message: 'Seed round direct mailing non-disclosure agreement graphical user interface rockstar.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a2.jpg',
        image: '/img/blog/b2.jpg',
    },
    {
        id: 5,
        name: 'Monica Geller',
        message: 'Beta prototype sales iPad gen-z marketing network effects value proposition',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a3.jpg',
        image: '/img/blog/b3.jpg',
    },
    {
        id: 6,
        name: 'Chandler Bing',
        message: 'Pitch termsheet backing validation focus release.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a1.jpg',
        image: '/img/blog/b1.jpg',
    },
    {
        id: 7,
        name: 'Rachel Green',
        message: 'Seed round direct mailing non-disclosure agreement graphical user interface rockstar.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a2.jpg',
        image: '/img/blog/b2.jpg',
    },
    {
        id: 8,
        name: 'Monica Geller',
        message: 'Beta prototype sales iPad gen-z marketing network effects value proposition',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a3.jpg',
        image: '/img/blog/b3.jpg',
    },
    {
        id: 9,
        name: 'Chandler Bing',
        message: 'Pitch termsheet backing validation focus release.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a1.jpg',
        image: '/img/blog/b1.jpg',
    },
    {
        id: 10,
        name: 'Rachel Green',
        message: 'Seed round direct mailing non-disclosure agreement graphical user interface rockstar.',
        category: 'Category',
        date: 'November 22, 2021',
        avatar: '/img/testimonials/a2.jpg',
        image: '/img/blog/b2.jpg',
    }
]